# Generated by Django 5.1.1 on 2024-09-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Asesor',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='cliente',
            new_name='asesor',
        ),
    ]
