# Generated by Django 5.1.1 on 2024-09-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_cliente_asesor_rename_cliente_mascota_asesor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='tamano',
            new_name='tamaño',
        ),
    ]
