# Generated by Django 5.1.1 on 2024-09-25 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_tamano_mascota_tamaño'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesor',
            name='mascota',
            field=models.ManyToManyField(blank=True, related_name='Asesor', to='core.mascota'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='comprado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='asesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='core.asesor'),
        ),
    ]
