# Generated by Django 5.1.1 on 2024-12-03 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_asesor_mascota_mascota_comprado_alter_mascota_asesor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asesor',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Asesor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
